### ISSUE TITLE
The README file should provide more details about Hypersistence Optimizer, as well as what is the goal of this repository

### ISSUE THREAD

**Issue by amihaiemil** [vladmihalcea/hypersistence-optimizer#93]
It would be nice to have clear usage guidelines right in the README, accompanied by the latest version (which should of course update automatically on each release).

**Comment by vladmihalcea** [comment]
It depends on what `README` file you are referring to. If you mean the `README` that comes bundled in the downloaded pack, then there's' already [an issue for that](https://github.com/vladmihalcea/hypersistence-optimizer/issues/84), that's going to be fixed in 2.1.

If you are referring to the [`README` file in this repository](https://github.com/vladmihalcea/hypersistence-optimizer/blob/master/README.md), then I'll review the current file and provide more details about where to get the right info.

**Comment by amihaiemil** [comment]
@vladmihalcea yes, I am referring to the README in the repo :)

**Comment by vladmihalcea** [comment]
The `README` in this repository will never contain the User Guide. The User Guide is already available:

- [online](https://vladmihalcea.com/hypersistence-optimizer/docs/user-guide/)
- offline, inside the downloadable package

This repository serves two purposes:

- it provides you examples of how you can use certain features or shows you ready-to-use configurations
- it allows creating issues for the product itself with the possibility of discussing the issues

Now, back to your initial statements:

> It would be nice to have clear usage guidelines right in the README, accompanied by the latest version

Indeed, it makes sense to add more info about what this repository is meant to and where to get more info about the actual product. In fact, that will be the goal of this issue.

>  (which should, of course, update automatically on each release).

Once this issue is fixed, there's actually nothing to automate as the `README` will be a short summary of what the product does and where to get more info about it.

**Comment by vladmihalcea** [comment]
The #84 is going to take care of this repository `README`, so this issue is closed as a duplicate.
